Repository konflux-ci/build-service, pull requests merged in 2023-08, with the labels that each got.

#185 Fix PaC pipeline reference
  .tekton/build-service-pull-request.yaml
  .tekton/build-service-push.yaml
Labels: lgtm, ok-to-test

#184 Provide git repository secret to build pipeline run
  config/rbac/role.yaml
  controllers/component_build_controller.go
  controllers/component_build_controller_simple_build.go
  controllers/component_build_controller_test.go
  controllers/component_build_controller_unit_test.go
  controllers/suite_test.go
  controllers/suite_util_gitprovider_test.go
  controllers/suite_util_test.go
  go.mod
  go.sum
  main.go
  pkg/boerrors/perror.go
  pkg/git/github/github_client.go
  pkg/git/github/github_helper.go
  pkg/git/github/github_helper_debug_test.go
  pkg/git/gitlab/gitlab_client.go
  pkg/git/gitlab/gitlab_helper.go
  pkg/git/gitlab/gitlab_helper_debug_test.go
  pkg/git/gitprovider/gitprovider.go
Labels: ok-to-test

#187 Improve permanent error message logging
  pkg/boerrors/perror.go
  pkg/boerrors/perror_test.go
Labels: lgtm

#188 Improve component git repository to SPI token match
  controllers/component_build_controller_simple_build.go
Labels: lgtm

#190 Increase test coverage in component_build_controller_simple_build.go and
  controllers/component_build_controller_simple_build.go
  controllers/component_build_controller_unit_test.go
  go.mod
  go.sum
  pkg/boerrors/perror_test.go
Labels: lgtm

#189 Remove old annotations
  controllers/component_build_controller.go
  controllers/component_build_controller_test.go
  controllers/suite_util_test.go
Labels: lgtm

#191 Increase test coverage in component_build_controller_pac.go and gitproviderfactory.go
  controllers/component_build_controller_unit_test.go
  pkg/git/gitproviderfactory/gitproviderfactory_test.go
Labels: lgtm

#194 Reuse existing PaC repository CR for multi component git repositories
  config/rbac/role.yaml
  controllers/component_build_controller.go
  controllers/component_build_controller_pac.go
  controllers/component_build_controller_test.go
  controllers/suite_util_test.go
  pkg/boerrors/perror.go
Labels: lgtm, ok-to-test
