Repository konflux-ci/build-service, pull requests merged in 2023-03, with the labels that each got.

#124 STONEBLD-760: make access token issue as permanent error
  controllers/component_build_controller_pac.go
  pkg/boerrors/perror.go
  pkg/boerrors/perror_test.go
  pkg/github/github_client.go
  pkg/github/github_helper.go
  pkg/gitlab/gitlab_client.go
  pkg/gitlab/gitlab_helper.go
Labels: approved, lgtm

#125 STONEBLD-870: git-tekton-resources-renovater
  config/rbac/role.yaml
  controllers/git_tekton_resources_renovater.go
  controllers/git_tekton_resources_renovater_test.go
  controllers/suite_test.go
  controllers/suite_util_test.go
  main.go
  pkg/github/github_client.go
Labels: approved

#128 STONEBLD-870: fix - missing job create permission
  config/rbac/role.yaml
  controllers/git_tekton_resources_renovater.go
Labels: approved, lgtm

#131 Improve GitHub application is not installed situation
  controllers/component_build_controller.go
  controllers/component_build_controller_pac.go
  controllers/component_build_controller_test.go
  pkg/github/github_client.go
  pkg/github/github_helper.go
  pkg/github/github_helper_debug_test.go
Labels: approved, lgtm

#126 STONEBLD-783: set on-target-branch to default branch properly
  controllers/component_build_controller_pac.go
  controllers/component_build_controller_test.go
  controllers/pac_pipelinerun_pruner_controller_test.go
  controllers/suite_util_test.go
  pkg/github/github_helper.go
  pkg/gitlab/gitlab_helper.go
Labels: approved

#130 STONEBLD-916: Limit update to quay.io/redhat-appstudio-tekton-catalog
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  controllers/git_tekton_resources_renovater.go
Labels: approved, lgtm

#134 Fix test: add missing mock
  controllers/component_build_controller_test.go
Labels: approved, lgtm

#133 STONEBLD-914: reduce scope to repositories in the cluster
  controllers/git_tekton_resources_renovater.go
  controllers/git_tekton_resources_renovater_test.go
  controllers/suite_util_test.go
  pkg/github/github_client.go
Labels: approved

#135 STONEBLD-914: Renovater - skip installations without repositories
  controllers/git_tekton_resources_renovater.go
Labels: approved, lgtm

#137 STONEBLD-818:Intergate Image Controller operator
  controllers/component_build_controller.go
  controllers/component_build_controller_common.go
  controllers/component_build_controller_initial_build.go
  controllers/component_build_controller_pac.go
  controllers/component_build_controller_test.go
  controllers/component_build_controller_unit_test.go
  controllers/suite_test.go
  pkg/boerrors/perror.go
Labels: approved, lgtm

#138 STONEBLD-764: close unmerged PaC merge request on component deletion
  controllers/component_build_controller_pac.go
  controllers/component_build_controller_test.go
  controllers/suite_util_test.go
  pkg/github/github_helper.go
  pkg/gitlab/gitlab_helper.go
Labels: lgtm

#140 Add two tests for permanent error
  controllers/component_build_controller_test.go
Labels: lgtm

#141 Fix reading data from image annotation
  controllers/component_build_controller_common.go
Labels: lgtm
